import assert from "node:assert/strict";
import { describe, it } from "node:test";

import base from "../base.js";
import nextjs from "../nextjs.js";
import { ruleIds } from "./lint.js";

describe("base preset", () => {
  it("accepts clean TypeScript", async () => {
    assert.deepEqual(await ruleIds(base, "library", "src/clean.ts"), []);
  });

  it("reports type imports, falsy-zero checks and floating promises", async () => {
    const ids = await ruleIds(base, "library", "src/violations.ts");
    assert.ok(ids.includes("@typescript-eslint/consistent-type-imports"));
    assert.ok(ids.includes("@typescript-eslint/strict-boolean-expressions"));
    assert.ok(ids.includes("@typescript-eslint/no-floating-promises"));
  });

  it("ignores the env.d.ts generated by catladder", async () => {
    // its eslint-disable comment names prettier/prettier, which is not
    // configured here and would fail the lint run if the file were linted
    const ids = await ruleIds(base, "library", "env.d.ts");
    assert.ok(!ids.includes("prettier/prettier"));
  });
});

describe("nextjs preset", () => {
  it("accepts a clean React component", async () => {
    assert.deepEqual(await ruleIds(nextjs, "nextjs", "app/clean.tsx"), []);
  });

  it("applies Next.js, React Hooks and type-aware rules to TSX", async () => {
    const ids = await ruleIds(nextjs, "nextjs", "app/violations.tsx");
    assert.ok(ids.includes("@next/next/no-img-element"));
    assert.ok(ids.includes("react-hooks/rules-of-hooks"));
    assert.ok(ids.includes("@typescript-eslint/strict-boolean-expressions"));
  });
});
