// -------------------------------------------------
// 🐱 🔨 This file is generated by catladder
// 🚨 Do not edit this file manually 🚨
// -------------------------------------------------

/* tslint:disable prettier/prettier */
/* eslint-disable prettier/prettier */
/* prettier-ignore */

export {}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ENV_SHORT: string
      APP_DIR: string
      ENV_TYPE: string
      DB_PORT: string
      TASK_QUEUE_PORT: string
      COMPOSE_PROJECT_NAME: string
    }
  }
}
