import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';

const implementation = fs.readFileSync(new URL('./preview-main.mjs', import.meta.url));
const git = (cwd, ...args) => execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();

async function fixture(t, withDb = true) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'evermore-preview-'));
  const remote = path.join(dir, 'remote.git');
  const source = path.join(dir, 'source');
  const preview = path.join(dir, 'preview with spaces');
  const bin = path.join(dir, 'bin');
  const callsFile = path.join(dir, 'calls.jsonl');
  fs.mkdirSync(source); fs.mkdirSync(bin);
  git(dir, 'init', '--bare', remote);
  git(source, 'init', '-b', 'main');
  git(source, 'config', 'user.email', 'test@example.com');
  git(source, 'config', 'user.name', 'Preview Test');
  fs.mkdirSync(path.join(source, 'scripts'));
  fs.writeFileSync(path.join(source, 'scripts/preview-main.mjs'), implementation);
  fs.writeFileSync(path.join(source, 'pnpm-lock.yaml'), 'lockfileVersion: 9\n');
  fs.writeFileSync(path.join(source, '.gitignore'), 'node_modules\n.env.local\n');
  fs.writeFileSync(path.join(source, 'page.txt'), 'first main');
  const writePackage = (db) => fs.writeFileSync(path.join(source, 'package.json'), JSON.stringify({ scripts: db ? { 'db:setup': 'stub' } : {} }));
  writePackage(withDb);
  const publish = () => { git(source, 'add', '.'); git(source, 'commit', '-m', 'Update main'); git(source, 'push', remote, 'main'); };
  publish();
  git(source, 'remote', 'add', 'origin', remote);
  let port;
  do {
    const server = net.createServer();
    await new Promise((resolve) => server.listen(0, resolve));
    port = server.address().port;
    await new Promise((resolve) => server.close(resolve));
  } while (port > 65436);
  fs.writeFileSync(path.join(bin, 'pnpm'), `#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const args = process.argv.slice(2);
fs.appendFileSync(process.env.TEST_CALLS, JSON.stringify({args, cwd:process.cwd(), port:process.env.BASE_PORT, db:process.env.DATABASE_URL})+'\\n');
if (process.env.TEST_FAIL === args.at(-1)) process.exit(7);
if (args[0] === 'install') fs.mkdirSync('node_modules', {recursive:true});
if (args[0] === 'catenv') fs.writeFileSync('.env.local', 'BASE_PORT='+process.env.BASE_PORT+'\\n');
if (args[0] === 'dev') {
  require('node:http').createServer((req,res)=>res.end(fs.readFileSync('page.txt'))).listen(Number(process.env.BASE_PORT));
}
`, { mode: 0o755 });
  const env = { ...process.env, PATH: `${bin}${path.delimiter}${process.env.PATH}`, PREVIEW_MAIN_DIR: preview, PREVIEW_MAIN_PORT: String(port), TEST_CALLS: callsFile, BASE_PORT: '9100', DATABASE_URL: 'postgresql://production/unsafe' };
  const run = (command, overrides = {}) => spawnSync(process.execPath, [path.join(source, 'scripts/preview-main.mjs'), command], { env: { ...env, ...overrides }, encoding: 'utf8', timeout: 20000 });
  const calls = () => fs.existsSync(callsFile) ? fs.readFileSync(callsFile, 'utf8').trim().split('\n').map(JSON.parse) : [];
  const state = () => JSON.parse(fs.readFileSync(path.join(git(preview, 'rev-parse', '--absolute-git-dir'), 'preview-main.json'), 'utf8'));
  t.after(() => {
    try { const pid = state().pid; if (pid) process.kill(-pid, 'SIGTERM'); } catch { /* No live server. */ }
    fs.rmSync(dir, { recursive: true, force: true });
  });
  return { source, preview, port, run, calls, state, publish, writePackage };
}
const passed = (result) => assert.equal(result.status, 0, result.stdout + result.stderr);

test('start and update keep a detached preview and a single running server while main changes', async (t) => {
  const f = await fixture(t);
  passed(f.run('start'));
  const pid = f.state().pid;
  assert.equal(await (await fetch(`http://localhost:${f.port}`)).text(), 'first main');
  assert.equal(git(f.preview, 'branch', '--show-current'), '');
  assert.equal(git(f.source, 'branch', '--show-current'), 'main');
  fs.mkdirSync(path.join(f.preview, '.claude/skills/catladder-cli'), { recursive: true });
  fs.writeFileSync(path.join(f.preview, '.claude/skills/catladder-cli/SKILL.md'), 'Generated by catenv');
  passed(f.run('start'));
  assert.equal(f.state().pid, pid);
  assert.equal(f.calls().filter(({ args }) => args[0] === 'dev').length, 1);
  assert.equal(f.calls().filter(({ args }) => args[0] === 'install').length, 1);
  assert.equal(f.calls().filter(({ args }) => args[0] === 'db:setup').length, 1);
  fs.writeFileSync(path.join(f.source, 'page.txt'), 'new main');
  f.publish();
  passed(f.run('update'));
  assert.equal(f.state().pid, pid);
  assert.equal(git(f.preview, 'rev-parse', 'HEAD'), git(f.source, 'rev-parse', 'HEAD'));
  assert.equal(await (await fetch(`http://localhost:${f.port}`)).text(), 'new main');
  assert.equal(f.calls().filter(({ args }) => args[0] === 'install').length, 1);
  fs.appendFileSync(path.join(f.source, 'pnpm-lock.yaml'), '# dependency change\n');
  f.publish();
  passed(f.run('update'));
  passed(f.run('update'));
  assert.equal(f.calls().filter(({ args }) => args[0] === 'install').length, 2);
  for (const call of f.calls()) {
    assert.equal(fs.realpathSync(call.cwd), fs.realpathSync(f.preview));
    assert.equal(call.port, String(f.port));
    assert.equal(call.db, `postgresql://evermore:evermore@localhost:${f.port + 30}/evermore`);
  }
  assert.ok(f.calls().some(({ args }) => args.at(-1) === 'migrate'));
});

test('update prepares a stopped preview and bootstraps DB once the DB package lands', async (t) => {
  const f = await fixture(t, false);
  passed(f.run('update'));
  assert.equal(f.calls().filter(({ args }) => args[0] === 'dev').length, 0);
  assert.equal(f.state().dbReady, undefined);
  f.writePackage(true); f.publish();
  passed(f.run('update'));
  passed(f.run('update'));
  assert.equal(f.calls().filter(({ args }) => args[0] === 'db:setup').length, 1);
  assert.equal(f.state().dbReady, true);
});

test('failed setup is retryable and never marked ready or launches the dev server', async (t) => {
  const f = await fixture(t);
  const failed = f.run('start', { TEST_FAIL: 'db:setup' });
  assert.notEqual(failed.status, 0);
  assert.equal(f.calls().filter(({ args }) => args[0] === 'dev').length, 0);
  passed(f.run('update'));
  assert.equal(f.calls().filter(({ args }) => args[0] === 'db:setup').length, 2);
  assert.equal(f.state().dbReady, true);
  assert.notEqual(f.run('update', { TEST_FAIL: 'migrate' }).status, 0);
});

test('update refuses dirty worktrees, checked-out branches, and changed persisted ports', async (t) => {
  const f = await fixture(t);
  passed(f.run('update'));
  fs.writeFileSync(path.join(f.preview, 'page.txt'), 'local work');
  assert.match(f.run('update').stderr, /local changes/);
  assert.equal(fs.readFileSync(path.join(f.preview, 'page.txt'), 'utf8'), 'local work');
  git(f.preview, 'restore', 'page.txt');
  git(f.preview, 'checkout', '-b', 'human-work');
  assert.match(f.run('update').stderr, /detached HEAD/);
  git(f.preview, 'checkout', '--detach');
  assert.match(f.run('update', { PREVIEW_MAIN_PORT: String(f.port + 1) }).stderr, /already persisted/);
  fs.writeFileSync(path.join(f.preview, 'incoming.txt'), 'local untracked work');
  fs.writeFileSync(path.join(f.source, 'incoming.txt'), 'incoming main');
  f.publish();
  assert.notEqual(f.run('update').status, 0);
  assert.equal(fs.readFileSync(path.join(f.preview, 'incoming.txt'), 'utf8'), 'local untracked work');
});

test('invalid commands and ports fail before creating a worktree', async (t) => {
  const f = await fixture(t);
  assert.notEqual(f.run('unknown').status, 0);
  assert.notEqual(f.run('start', { PREVIEW_MAIN_PORT: 'invalid' }).status, 0);
  assert.equal(fs.existsSync(f.preview), false);
  passed(f.run('--help'));
});

test('a busy port prevents a second server from launching', async (t) => {
  const f = await fixture(t);
  const server = net.createServer();
  await new Promise((resolve) => server.listen(f.port, resolve));
  try {
    assert.notEqual(f.run('start').status, 0);
    assert.equal(f.calls().filter(({ args }) => args[0] === 'dev').length, 0);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
});

test('default directory is beside the main checkout even when invoked from a linked worktree', async (t) => {
  const f = await fixture(t);
  const caller = path.join(f.source, '../caller');
  git(f.source, 'worktree', 'add', '--detach', caller);
  const result = spawnSync(process.execPath, [path.join(caller, 'scripts/preview-main.mjs'), 'update'], {
    env: { ...process.env, PATH: `${path.join(f.source, '../bin')}${path.delimiter}${process.env.PATH}`, PREVIEW_MAIN_PORT: String(f.port), TEST_CALLS: path.join(f.source, '../calls.jsonl'), PREVIEW_MAIN_DIR: undefined },
    encoding: 'utf8', timeout: 20000,
  });
  passed(result);
  const expected = path.join(f.source, '../evermore-preview');
  assert.equal(git(expected, 'branch', '--show-current'), '');
  assert.equal(git(expected, 'rev-parse', 'HEAD'), git(f.source, 'rev-parse', 'HEAD'));
  assert.equal(fs.existsSync(path.join(caller, '../evermore-preview')), true);
});

test('failed dev launch reports failure and a later start recovers', async (t) => {
  const f = await fixture(t);
  const failed = f.run('start', { TEST_FAIL: 'dev' });
  assert.notEqual(failed.status, 0);
  assert.match(failed.stderr, /Dev server did not become ready/);
  passed(f.run('start'));
  assert.equal(await (await fetch(`http://localhost:${f.port}`)).text(), 'first main');
});
