// -------------------------------------------------
// 🐱 🔨 This file is generated by catladder
// 🚨 Do not edit this file manually 🚨
// -------------------------------------------------

/* tslint:disable prettier/prettier */
/* eslint-disable prettier/prettier */
/* prettier-ignore */

export {}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ENV_SHORT: string
      APP_DIR: string
      ENV_TYPE: string
      ROOT_URL: string
      HOSTNAME: string
      HOSTNAME_INTERNAL: string
      ROOT_URL_INTERNAL: string
      PORT: string
    }
  }
}
